// Service-Worker: offline spielbar (Solo/zu zweit), Cache-Busting über Inhalts-Hash (tools/update_sw.py)
const VERSION = 'f34cdc704d';
const CACHE = 'spielebox-' + VERSION;
const ASSETS = [
  './',
  'assets/cards/de/EA@2x.webp',
  'assets/cards/de/EK@2x.webp',
  'assets/cards/de/EO@2x.webp',
  'assets/cards/de/EU@2x.webp',
  'assets/cards/de/EZ@2x.webp',
  'assets/cards/de/HA@2x.webp',
  'assets/cards/de/HK@2x.webp',
  'assets/cards/de/HO@2x.webp',
  'assets/cards/de/HU@2x.webp',
  'assets/cards/de/HZ@2x.webp',
  'assets/cards/de/LA@2x.webp',
  'assets/cards/de/LK@2x.webp',
  'assets/cards/de/LO@2x.webp',
  'assets/cards/de/LU@2x.webp',
  'assets/cards/de/LZ@2x.webp',
  'assets/cards/de/SA@2x.webp',
  'assets/cards/de/SK@2x.webp',
  'assets/cards/de/SO@2x.webp',
  'assets/cards/de/SU@2x.webp',
  'assets/cards/de/SZ@2x.webp',
  'assets/cards/fr/2C@2x.webp',
  'assets/cards/fr/2D@2x.webp',
  'assets/cards/fr/2H@2x.webp',
  'assets/cards/fr/2S@2x.webp',
  'assets/cards/fr/3C@2x.webp',
  'assets/cards/fr/3D@2x.webp',
  'assets/cards/fr/3H@2x.webp',
  'assets/cards/fr/3S@2x.webp',
  'assets/cards/fr/4C@2x.webp',
  'assets/cards/fr/4D@2x.webp',
  'assets/cards/fr/4H@2x.webp',
  'assets/cards/fr/4S@2x.webp',
  'assets/cards/fr/5C@2x.webp',
  'assets/cards/fr/5D@2x.webp',
  'assets/cards/fr/5H@2x.webp',
  'assets/cards/fr/5S@2x.webp',
  'assets/cards/fr/6C@2x.webp',
  'assets/cards/fr/6D@2x.webp',
  'assets/cards/fr/6H@2x.webp',
  'assets/cards/fr/6S@2x.webp',
  'assets/cards/fr/7C@2x.webp',
  'assets/cards/fr/7D@2x.webp',
  'assets/cards/fr/7H@2x.webp',
  'assets/cards/fr/7S@2x.webp',
  'assets/cards/fr/8C@2x.webp',
  'assets/cards/fr/8D@2x.webp',
  'assets/cards/fr/8H@2x.webp',
  'assets/cards/fr/8S@2x.webp',
  'assets/cards/fr/9C@2x.webp',
  'assets/cards/fr/9D@2x.webp',
  'assets/cards/fr/9H@2x.webp',
  'assets/cards/fr/9S@2x.webp',
  'assets/cards/fr/AC@2x.webp',
  'assets/cards/fr/AD@2x.webp',
  'assets/cards/fr/AH@2x.webp',
  'assets/cards/fr/AS@2x.webp',
  'assets/cards/fr/JC@2x.webp',
  'assets/cards/fr/JD@2x.webp',
  'assets/cards/fr/JH@2x.webp',
  'assets/cards/fr/JS@2x.webp',
  'assets/cards/fr/KC@2x.webp',
  'assets/cards/fr/KD@2x.webp',
  'assets/cards/fr/KH@2x.webp',
  'assets/cards/fr/KS@2x.webp',
  'assets/cards/fr/QC@2x.webp',
  'assets/cards/fr/QD@2x.webp',
  'assets/cards/fr/QH@2x.webp',
  'assets/cards/fr/QS@2x.webp',
  'assets/cards/fr/TC@2x.webp',
  'assets/cards/fr/TD@2x.webp',
  'assets/cards/fr/TH@2x.webp',
  'assets/cards/fr/TS@2x.webp',
  'assets/pieces/bB.svg',
  'assets/pieces/bK.svg',
  'assets/pieces/bN.svg',
  'assets/pieces/bP.svg',
  'assets/pieces/bQ.svg',
  'assets/pieces/bR.svg',
  'assets/pieces/wB.svg',
  'assets/pieces/wK.svg',
  'assets/pieces/wN.svg',
  'assets/pieces/wP.svg',
  'assets/pieces/wQ.svg',
  'assets/pieces/wR.svg',
  'assets/wood/dark.webp',
  'assets/wood/frame.webp',
  'assets/wood/light.webp',
  'css/style.css',
  'icons/apple-touch-icon.png',
  'icons/favicon-64.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-512.png',
  'index.html',
  'lib/chess.js',
  'lib/trystero.js',
  'manifest.webmanifest',
  'src/app.js',
  'src/botclient.js',
  'src/botworker.js',
  'src/build.js',
  'src/games/backgammon/bot.js',
  'src/games/backgammon/engine.js',
  'src/games/backgammon/view.js',
  'src/games/blackjack/bot.js',
  'src/games/blackjack/engine.js',
  'src/games/blackjack/view.js',
  'src/games/dame/bot.js',
  'src/games/dame/engine.js',
  'src/games/dame/view.js',
  'src/games/halma/bot.js',
  'src/games/halma/engine.js',
  'src/games/halma/view.js',
  'src/games/muehle/bot.js',
  'src/games/muehle/engine.js',
  'src/games/muehle/view.js',
  'src/games/registry.js',
  'src/games/schach/bot.js',
  'src/games/schach/engine.js',
  'src/games/schach/view.js',
  'src/games/schnapsen/bot.js',
  'src/games/schnapsen/engine.js',
  'src/games/schnapsen/view.js',
  'src/net/crypto.js',
  'src/net/fair.js',
  'src/net/netlink.js',
  'src/net/relaychannel.js',
  'src/net/relays.js',
  'src/net/table.js',
  'src/rng.js',
  'src/store.js',
  'src/ui/cards.js',
  'src/ui/dom.js',
  'src/ui/gameui.js',
  'src/ui/lobby.js',
  'src/ui/seatcolors.js',
  'src/ui/svg.js',
  'src/ui/tablescreen.js',
  'src/ui/texts.js',
  'src/words.js'
];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('spielebox-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(caches.match('index.html', { cacheName: CACHE }).then((r) => r || fetch(req)));
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE, ignoreSearch: true }).then((r) => r || fetch(req).then((res) => {
    if (res.ok) { const cp = res.clone(); caches.open(CACHE).then((c) => c.put(req, cp)); }
    return res;
  })));
});
